MainFiles = main.cpp gameWrapper.cpp header.h
SOURCEFiles = main.cpp gameWrapper.cpp
TESTFiles = main.cpp TestFunctions.cpp gameWrapper.cpp


main: $(MainFiles)
	g++ -std=c++17 -Wall -g $(SOURCEFiles) -o main
	


test:



